### ISSUE TITLE
No commits today

### ISSUE THREAD

**Issue by kimo** [Kameshdangeti/java_projects#1]

**Comment by Kameshdangeti** [comment]
That is because, of ;
1.)I was not feeling well Yesterday. I was Suffering continues coughs and Cold.
2.)And so, Yesterday I Just revised the Link You sent. And Took Rest From Afternoon,
  But I am Feeling Good now  so, I Started My Work.
       Thank you

**Comment by kimo** [comment]
Alright. Cool.
